# Generated by Django 4.2.2 on 2023-06-29 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahalla', '0004_alter_people_id_distirick_alter_people_id_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='id_distirick',
            new_name='id_districk',
        ),
    ]
