# Generated by Django 4.2.2 on 2023-06-29 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mahalla', '0005_rename_id_distirick_people_id_districk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id_user'),
        ),
    ]
