# Generated by Django 4.2.2 on 2023-06-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahalla', '0007_alter_tasks_id_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date_line',
            field=models.DateField(blank=True, null=True),
        ),
    ]
