# Generated by Django 4.2.2 on 2023-06-30 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahalla', '0008_alter_tasks_date_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='id_people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='mahalla.people'),
        ),
    ]
