# Generated by Django 4.2.2 on 2023-07-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahalla', '0009_alter_tasks_id_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='doc/'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='is_task',
            field=models.BooleanField(default=False),
        ),
    ]
