# Generated by Django 4.2.2 on 2023-06-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custumusers',
            name='position',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
