# Generated by Django 4.2.2 on 2023-07-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_custumusers_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='id_sektor',
        ),
        migrations.AddField(
            model_name='district',
            name='id_sektor',
            field=models.ManyToManyField(blank=True, null=True, to='authen.sektor'),
        ),
    ]
