# Generated by Django 4.2.2 on 2023-07-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_remove_district_id_sektor_district_id_sektor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='id_sektor',
            field=models.ManyToManyField(blank=True, to='authen.sektor'),
        ),
    ]
